### PR TITLE
Close #15: Replace CodeMirror w/ Monaco

### LINKED ISSUE #15: Consider replacing CodeMirror with Monaco
The official CodeMirror 6 reference says it is accessible to screen readers, but unfortunately, it is not as accessible as Monaco. Please consider replacing CodeMirror with Monaco to make this extension more inclusive.

### PR DESCRIPTION
**Pull request by jooyoungseo**
- [x] Replace CodeMirror -> Monaco.

- [x] Add Shift+Enter to run current cell.

- [x] Add Ctrl+Enter to run selected code.

- [x] Add `aria-live` to code output div to automatically announce the result to screen readers.

- [x] Tested with screen readers.

### CODE REVIEW

**Comment by coatless** [comment]
@jooyoungseo thanks! I'll test it a bit more in-depth later tonight.

**Comment by jooyoungseo** [comment]
@coatless -- Although I have made the basic functionality work for screen readers, the graphic output does not seem to work. I need your help with that. Dealing with canvas is visually challenging to me.

Printing graphic output as an svg object via {svglite} 
would be more accessible in the long run.

**Comment by coatless** [comment]
@jooyoungseo no worries on the canvas. I've tweaked a few things to:

1. remove empty height between code editor and output;
2. allow for the dynamic growth of a code window.
3. disabled the minimap that was appearing on the right-hand side. 

Could you give me push access onto your fork so that I can upload the changes?

**Comment by jooyoungseo** [comment]
@coatless -- I have invited you to my fork repo as a collaborator.

**Comment by coatless** [comment]
@jooyoungseo thanks! If you have a moment later today, please try out the `webr-demo.qmd` file at the top-level of the repository within the branch.

**Comment by jooyoungseo** [comment]
@coatless -- It works nicely on my end! I think this PR is ready to get merged. I have some more ideas to make this extension more accessible, but I will need to create separate issues.

**Pull request merged**
